Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: CI
+name: Assign a PR to the person who created it
 
 on:
   pull_request:
@@ -9,11 +9,17 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-     # Runs a single command using the runners shell
-      - name: Run a one-line script
+      - name: Check if a user can be assigned
+        run: |
+          HTTP_RESP_CODE=$(curl -o /dev/null  -w "%{http_code}" -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/assignees/${{ github.event.sender.login }})
+          if [[ $HTTP_RESP_CODE != 203 ]]; then
+            echo "Check if a user can be assigned failed ($HTTP_RESP_CODE)"
+            exit 1
+          fi
+      - name: Add assignees to an PR
         run: |
           HTTP_RESP_CODE=$(curl -o /dev/null  -w "%{http_code}" -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/assignees -d '{"assignees":["${{ github.event.sender.login }}"]}')
-          if [[ $HTTP_RESP_CODE != 200 ]]; then
+          if [[ $HTTP_RESP_CODE != 201 ]]; then
             echo "Add assignees to an PR failed ($HTTP_RESP_CODE)"
             exit 1
           fi
